services:
  - type: web
    name: tourism-diary-app  # Your service name
    runtime: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    env: java
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tourism-postgres  # Your PostgreSQL DB name
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: production
