services:
  - type: web
    name: tourism-diary-app
    runtime: docker  # Only this line is needed for Docker runtime
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://tramway.proxy.rlwy.net:20287/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: CIyjNMMxGaLxUVJyyYuPaPlucvSAvMnia
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
